TOP_DIRECTORY=../../..

CXX_LDFLAGS= \

TEST1=t_test1
TEST2=t_test2

TEST_SOURCES= \
	$(TEST1).cpp  \
	$(TEST2).cpp \

TEST_EXECUTABLES= \
	$(TEST1) \
	$(TEST2) \

-include $(TOP_DIRECTORY)/mk/test.mk

